### ISSUE TITLE
SingleStat

### ISSUE THREAD

**Issue by dcohen24** [GoshPosh/grafana-meta-queries#10]
I find then when I use a meta query for as single stat, (say for division) I wind up with 0, where as if I do the same division on a time series graph, metaquery performs as expected.

Here is one such example: The metaquery singlestat on the right, is the same division as the one in the time series, and should be the division of the 2 single-stats to the left
![image](https://user-images.githubusercontent.com/16311507/34450313-dd7928a4-ecd3-11e7-802b-4cbc573554ef.png)

**Comment by notz** [comment]
Perhaps the problem is your choosen timeframe. Arimethic between two queries is not working if you choose somthing like "the last 7 days". Because the queries are executed with a different "now" timestamp, so the series don't have the same timestamp. It's also not working if their is only one datapoint.

The problem is here:
```
var resultsHash= {};
              for(var i=0;i<results.length;i++){

                  var resultByQuery = results[i];

                  for(var j=0;j<resultByQuery.data.length;j++){
                      var resultByQueryMetric = resultByQuery.data[j];
                      var metricName = resultByQueryMetric.target;
                      if(resultByQueryMetric.datapoints){
                          for(var k=0;k<resultByQueryMetric.datapoints.length;k++){
                              var datapoint = resultByQueryMetric.datapoints[k];
                              resultsHash[datapoint[1]] = resultsHash[datapoint[1]] || [];
                              resultsHash[datapoint[1]][i] = resultsHash[datapoint[1]][i] || {};
                              resultsHash[datapoint[1]][i][metricName] = datapoint[0]
                          }
                      }
                  }

              }
```

Their must be an round & match on the timestamp or at least if their is only one datapoint a common timestamp.

**Comment by dcohen24** [comment]
ah... totally right... I was using a single data point... when I moved it to something with >1 datapoint, all good
